dist: xenial
language: r
sudo: true
before_install:
  - sudo apt-get install python3 python3-pip python3-pandas
  - pip3 install bibtexparser
# command to run tests
script:
  - make
cache: packages
r_packages:
  - pacman
  - here
  - data.table
  - DT
  - tidyverse
deploy:
  # Use Github pages deploy process
  provider: pages
  # Keep builded pages
  skip-cleanup: true
  # Directory where your generated files are located
  local_dir: public
  # Github security/auth token (added in Travis Settings)
  github-token: $GITHUB_TOKEN
  # Incremental commit to keep old build/files from previous deployments
  keep-history: true
  # Git branch on which it should deploy (master, gh-pages, foo...)
  target_branch: gh-pages
#  on:
#    # Which branch on commit/push will trigger deployment
#    branch: master
