dist: bionic
language: r
sudo: true
latex: false
git:
  submodules: false
before_install:
  # install python 3.8
  # see https://docs.python-guide.org/starting/install3/linux/
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository --yes ppa:deadsnakes/ppa
  - sudo apt-get update
  - sudo apt-get install python3.8.6 python3-pip python3-pandas python3-setuptools
  - pip3 install --upgrade pip
  - pip install -r requirements.txt
  #- sudo apt-get install python3 python3-pip python3-pandas python3-setuptools
  #- pip3 install bibtexparser==1.2.0
  #- pip3 install pyparsing==2.4.7
  #- pip3 install future==0.18.2
# command to run tests
script:
  - make all
cache: packages
r_packages:
  - pacman
  - here
  - data.table
  - DT
  - tidyverse
  - lemon
  - bookdown
  - assertr
deploy:
  # Use Github pages deploy process
  provider: pages
  # Keep builded pages
  skip-cleanup: true
  # Directory where your generated files are located
  local_dir: public
  # Github security/auth token (added in Travis Settings)
  github-token: $GITHUB_TOKEN
  # Incremental commit to keep old build/files from previous deployments
  keep-history: true
  # Git branch on which it should deploy (master, gh-pages, foo...)
  target_branch: gh-pages
  on:
    # Which branch on commit/push will trigger deployment
    branch: master
